/**
 * Application-wide error code system
 * Format: CATEGORY_NUMBER
 *
 * Usage: throw new HttpException({ code: ErrorCode.AUTH_001, message: '...' }, status)
 */
export enum ErrorCode {
  // Authentication Errors (001-099)
  AUTH_INVALID_CREDENTIALS = 'AUTH_001',
  AUTH_TOKEN_EXPIRED = 'AUTH_002',
  AUTH_TOKEN_INVALID = 'AUTH_003',
  AUTH_REFRESH_TOKEN_REVOKED = 'AUTH_004',
  AUTH_ACCOUNT_SUSPENDED = 'AUTH_005',
  AUTH_EMAIL_NOT_VERIFIED = 'AUTH_006',
  AUTH_TOO_MANY_ATTEMPTS = 'AUTH_007',
  AUTH_ACCOUNT_LOCKED = 'AUTH_008',

  // User Errors (100-199)
  USER_NOT_FOUND = 'USER_001',
  USER_EMAIL_EXISTS = 'USER_002',
  USER_INVALID_ROLE = 'USER_003',
  USER_CANNOT_MODIFY = 'USER_004',

  // Analysis Errors (200-299)
  ANALYSIS_NOT_FOUND = 'ANALYSIS_001',
  ANALYSIS_TEXT_TOO_SHORT = 'ANALYSIS_002',
  ANALYSIS_TEXT_TOO_LONG = 'ANALYSIS_003',
  ANALYSIS_INVALID_CONTEXT = 'ANALYSIS_004',
  ANALYSIS_CONTENT_EMPTY = 'ANALYSIS_005',
  ANALYSIS_FAILED = 'ANALYSIS_006',

  // Recommendation Errors (300-399)
  RECOMMENDATION_NOT_FOUND = 'RECO_001',
  RECOMMENDATION_GENERATION_FAILED = 'RECO_002',

  // Validation Errors (400-499)
  VALIDATION_FAILED = 'VAL_001',
  VALIDATION_INVALID_FORMAT = 'VAL_002',
  VALIDATION_REQUIRED_FIELD = 'VAL_003',

  // Permission Errors (500-599)
  PERMISSION_DENIED = 'PERM_001',
  RESOURCE_NOT_OWNED = 'PERM_002',
  ADMIN_ONLY = 'PERM_003',

  // System Errors (600-699)
  INTERNAL_ERROR = 'SYS_001',
  SERVICE_UNAVAILABLE = 'SYS_002',
  DATABASE_ERROR = 'SYS_003',
  EXTERNAL_SERVICE_ERROR = 'SYS_004',

  // Rate Limiting Errors (700-799)
  RATE_LIMIT_EXCEEDED = 'RATE_001',
  BRUTE_FORCE_DETECTED = 'RATE_002',
}
